#!/usr/bin/evn python
import sys
if len(sys.argv) != 2:
    print "Usage:"
    print "%s filename" % sys.argv[0]
    exit(1)
fp = open(sys.argv[1], 'r')

for line in fp:
    line = line.rstrip()
    print line
fp.close() 

